# Generated by Django 5.2.4 on 2025-07-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.UUIDField(blank=True, help_text="UUID de l'entité liée (tâche, projet, etc.)", null=True),
        ),
    ]
